guestbook/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

guestbook/web/urls.py
from django.urls import path
from django.views.generic import RedirectView
from .views import *

urlpatterns = [
    path('', RedirectView.as_view(url='message/')),
    path('message/', MessageList.as_view()),
    path('message/<int:pk>/', MessageDetail.as_view()),
    path('message/create/', MessageCreate.as_view()),
    path('message/<int:pk>/delete/', MessageDelete.as_view()),
]

web/models.py
from django.db import models

# Create your models here.

class Message(models.Model):
    user = models.CharField("姓名", max_length=50)
    subject = models.CharField("主旨", max_length=200)
    content = models.TextField("內容")
    publication_date = models.DateTimeField("留言日期", auto_now_add=True)

    def __str__(self):
        return self.subject

web/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse
from .models import Message

# Create your views here.
class MessageList(ListView):
    model = Message
    ordering = ['-id']      # 以 id 欄位值由大至小反向排序

# 留言檢視
class MessageDetail(DetailView):
    model = Message

# 新增留言
class MessageCreate(CreateView):
    model = Message
    fields = ['user', 'subject', 'content']     # 僅顯示 user, subject, content 這 3 個欄位
    success_url = '/message/'                   # 新增成功後，導向留言列表
    template_name = 'form.html'                 # 指定欲使用的頁面範本

    # 刪除留言
class MessageDelete(DeleteView):
    model = Message
    success_url = '/message/'                # 刪除成功返回留言列表
    template_name = 'confirm_delete.html'

guestbook/web/templates/base.html
<!DOCTYPE html>
<html lang="zh-hant">
<head>
    <title>留言板</title>
</head>
<body>
  <h1>留言板</h1>
  <div>
    <a href="/">首頁</a>
    <a href="/message/create/">新增留言</a>
    {% if user.is_authenticated %}
    {{ user.username }} <a href="{% url 'logout' %}">登出</a>
    {% else %}
      <a href="{% url 'login' %}">登入</a>
    {% endif %}
  </div>
  <div>
    {% block content %}{% endblock %}
  </div>
</body>
</html>

guestbook/web/templates/confirm_delete.html
{% extends "base.html" %}

{% block content %}
<h2>刪除記錄</h2>
<p>您確定要刪除「{{ object }}」這筆記錄嗎?</p>
<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="是的，我要刪除" />
</form>
{% endblock %

guestbook/web/templates/form.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="送出" />
</form>
{% endblock %}

guestbook/web/templates/web/pessage_list.html
{% extends 'base.html' %}

{% block content %}
<ul>
  {% for message in message_list %}
  <li>
    {{ message.publication_date }}
    {% if user.is_authenticated %}
      <a href="{{ message.id }}/delete/">刪除</a>
    {% endif %}
    <a href="{{ message.id }}">{{ message.subject }}</a>
  </li>
  {% endfor %}
</ul>
{% endblock %}

guestbook/web/templates/web/peswsage_detal.html
{% extends "base.html" %}

{% block content %}
  <h2>姓名</h2>
  {{ message.user }}<BR>
  <h2>主旨</h2>
  {{ message.subject }}<BR>
  <h2>內容</h2>
  {{ message.content|linebreaks }}<BR>
{% endblock %}